---
title: "When Big Business Loses (?) : The Political Economy of Regulation in the Context of Noisy Politics"
format: 
  beamer:
    keep-tex: true
    toc: false
    slide-level: 2
    incremental: FALSE
    theme: Rochester
editor: visual
author:
  - Oscar Dumas
  - Hyung Won Kim
  - Nikolaos Vichos
bibliography: references.bib
---

## Overview of Presentation {.fragile}

1.  Introduction
2.  Theoretical Framework and Important Concepts: Noisy Politics
3.  Side-By-Side: Paper Summaries and Critical Discussion
4.  Synthesis: What Unites the Two Papers?
5.  Contextualization: Noisy Politics and the Political Economy of Regulation
6.  Conclusion and Discussion

# Introduction

## Texts

-   Massoc, Elsa. 2019. “Taxing Stock Transfers in the First Golden Age of Financial Capitalism: Political Salience and the Limits on the Power of Finance.” *Socio-Economic Review* 17 (3): 503–22. https://doi.org/10.1093/ser/mwx039.
-   Feldmann, Magnus, and Glenn Morgan. 2021. “Brexit and British Business Elites: Business Power and Noisy Politics.” *Politics & Society* 49 (1): 107–31. https://doi.org/10.1177/0032329220985692.

## Research Focus

### @massoc2019 :

-   Why did powerful financial actors fail to prevent the adoption of stock-transfer taxes in France and New York?
-   **Focus**: how public discontent + political framing raised salience and undermined “quiet politics.”

### @feldmann2021:

-   Under what conditions can business elites be effective in a context of noisy politics, and why did their influence differ between 1975 and 2016?
-   **Focus**: how incentives, legitimacy, and cohesion shape business influence in high-politicization referendum campaigns.

## What brings these papers together?

Both papers examine how political visibility and public contestation reshape business/financial influence

-   @massoc2019 shows how politicization of a tax issue enabled politicians to override strong financial lobbying.

-   @feldmann2021 analyze how changing political conditions over time affect business effectiveness in high-visibility referendum campaigns.\

### **Common Question**

-   *Under what conditions do business actors struggle to assert influence?*

## Culpepper’s Framework: Quiet vs. Noisy Politics

**Core hypothesis:** The more the public cares about an issue, the less business can exercise disproportionate influence over regulation. Business power decreases as political salience increases.


\small

| **Quiet Politics** | **Noisy Politics** |
|------------------------------------|------------------------------------|
| Issues are technically complex and low in public salience. Business dominates through expertise monopoly and structural dependence. | Issues become publicly salient and politicized. Media attention and public engagement constrain business influence and organizations become cautious and may avoid public positioning. |

\normalsize

Three forms of business power:

1.  Structural: State depends on business for investment and employment.
2.  Instrumental: Lobbying, campaign contributions, expertise access, revolving doors.
3.  Ideational: Cognitive capture through accepted narratives (“what is good for business is good for everyone”)

The challenge: Business power persists even in noisy politics through technical complexity, strategic network-building, and control of core growth sectors.

## Bibliography {.allowframebreaks}

::: {#refs}
:::
